const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');const path=require('node:path');const root=path.join(__dirname,'../web');const tick=()=>new Promise(r=>setTimeout(r,15));
function open(seed={},fetchImpl,options={}){const dom=new JSDOM(fs.readFileSync(path.join(root,'shipping-calculator.html'),'utf8'),{url:options.url||'https://live.test/shipping-calculator.html',runScripts:'outside-only'});const w=dom.window;if(options.storage)Object.defineProperty(w,'localStorage',{value:options.storage});for(const [k,v]of Object.entries(seed))w.localStorage.setItem(k,v);w.fetch=fetchImpl|| (async()=>({status:404,json:async()=>({})}));for(const file of ['persistence.js','shipping.js','part-parcel.js','part-lookup-ui.js','workspace-sync.js','research-queue.js','shipping-calculator.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));return dom;}
function input(w,selector,value){const el=w.document.querySelector(selector);assert.ok(el,selector);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));return el;}
test('shipping edit saves immediately with durable pending sync and reopens',async()=>{let dom=open();const w=dom.window;input(w,'[name=weightKg]','12.');assert.equal(JSON.parse(w.localStorage.getItem('part-scout-shipping-draft-v1')).weightKg,'12.');const meta=JSON.parse(w.localStorage.getItem('part-scout-sync-v1:shipping'));assert.equal(meta.pending.weightKg,'12.');const seed=Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));dom.window.close();dom=open(seed);assert.equal(dom.window.document.querySelector('[name=weightKg]').value,'12.');dom.window.close();});
test('queue add and explicit resume preserve per-item drafts without supplier requests',async()=>{const urls=[];const dom=open({},async url=>{urls.push(url);return {status:404,json:async()=>({})};});const w=dom.window;const form=w.document.querySelector('[data-queue-add]');assert.ok(form);for(const part of ['90915-10001','90915-10002']){form.elements.partNumber.value=part;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}const resume=i=>w.document.querySelectorAll('.research-item')[i].querySelector('button').click();resume(0);assert.equal(w.document.querySelector('[data-lookup-field=part]').value,'90915-10001');input(w,'[name=weightKg]','12.');resume(1);input(w,'[name=weightKg]','3');resume(0);assert.equal(w.document.querySelector('[name=weightKg]').value,'12.');assert.ok(urls.every(url=>url.startsWith('/api/workspace/')));dom.window.close();});
test('successful cloud receive invalidates a pending import and preserves focused input until blur',async()=>{let remote={schemaVersion:1,userKey:'alice',revision:0,data:null,updatedAt:null};const dom=open({},async()=>({status:200,json:async()=>structuredClone(remote)}));const w=dom.window;await tick();let finish;const file={size:100,text:()=>new Promise(r=>finish=r)};const fileInput=w.document.querySelector('#calc-file');Object.defineProperty(fileInput,'files',{value:[file]});fileInput.dispatchEvent(new w.Event('change'));remote={...remote,revision:1,data:{region:'US48',weightKg:'7'},updatedAt:new Date().toISOString()};w.document.querySelector('#shipping-sync [data-sync-now]').click();await tick();assert.equal(w.document.querySelector('[name=weightKg]').value,'7');finish(JSON.stringify({format:'part-scout-shipping-draft-v1',data:{weightKg:'99'}}));await tick();assert.equal(w.document.querySelector('[name=weightKg]').value,'7');const focused=w.document.querySelector('[name=weightKg]');focused.focus();remote={...remote,revision:2,data:{region:'US48',weightKg:'8'}};w.document.querySelector('#shipping-sync [data-sync-now]').click();await tick();assert.equal(focused.value,'7');focused.blur();w.document.querySelector('#shipping-sync [data-sync-now]').click();await tick();assert.equal(focused.value,'8');dom.window.close();});
test('service worker excludes every API request before touching caches',()=>{const source=fs.readFileSync(path.join(root,'sw.js'),'utf8');assert.match(source,/url\.pathname\.startsWith\("\/api\/"\)/);assert.ok(source.indexOf('url.pathname.startsWith("/api/")')<source.indexOf('if (isDynamicDataUrl(url.href))'));assert.match(source,/workspace-sync\.js/);assert.match(source,/research-queue\.js/);});
test('main initial defaults and timestamp-only page lifecycle do not create cloud writes',async()=>{const requests=[];const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://live.test/',runScripts:'outside-only'});const w=dom.window;w.scrollTo=()=>{};w.fetch=async(url,opts={})=>{requests.push({url,method:opts.method});return url.startsWith('/api/workspace/')?{status:200,json:async()=>({schemaVersion:1,userKey:'alice',revision:0,data:null,updatedAt:null})}:{ok:false,json:async()=>({})};};for(const file of ['persistence.js','shipping.js','part-parcel.js','part-lookup-ui.js','workspace-sync.js','research-queue.js','app.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));await tick();w.dispatchEvent(new w.Event('pagehide'));w.document.querySelector('#main-sync [data-sync-now]').click();await tick();assert.equal(requests.filter(r=>r.method==='PUT').length,0);assert.equal(w.localStorage.getItem('part-scout-user-v1'),null);assert.equal(w.document.querySelectorAll('.product-card').length,0);dom.window.close();});
test('version exports use existing main/shipping backup formats and queue restore is accessible',()=>{const Sync=require('../web/workspace-sync.js');assert.deepEqual(Sync.versionBackup('main',{settings:{}}),{format:'part-scout-backup',version:1,data:{settings:{}}});assert.deepEqual(Sync.versionBackup('shipping',{weightKg:'1'}),{format:'part-scout-shipping-draft-v1',data:{weightKg:'1'}});const dom=open();assert.ok(dom.window.document.querySelector('[data-queue-import]'));assert.ok(dom.window.document.querySelector('[data-sync-version]'));dom.window.close();});
test('queue selected backup restores validated data and rejects stale import after an edit',async()=>{const dom=open(),w=dom.window;const fileInput=w.document.querySelector('[data-queue-file]');const data={version:1,activeId:null,items:[{id:'TOYOTA:90915-10001',manufacturer:'TOYOTA',partNumber:'90915-10001',status:'confirm',note:'確認する',draft:null}]};let file={size:200,text:async()=>JSON.stringify({format:'part-scout-research-queue-v1',data})};Object.defineProperty(fileInput,'files',{configurable:true,get:()=>[file]});fileInput.dispatchEvent(new w.Event('change'));await tick();assert.match(w.document.querySelector('.research-item').textContent,/90915-10001/);let finish;file={size:200,text:()=>new Promise(r=>finish=r)};fileInput.dispatchEvent(new w.Event('change'));input(w,'.research-item textarea','新しいメモ');finish(JSON.stringify({format:'part-scout-research-queue-v1',data}));await tick();assert.equal(JSON.parse(w.localStorage.getItem('part-scout-research-queue-v1')).items[0].note,'新しいメモ');assert.match(w.document.querySelector('[data-queue-message]').textContent,/復元を中止/);dom.window.close();});
const shippingKey='part-scout-shipping-draft-v1',queueKey='part-scout-research-queue-v1';
function draft(part,weight){const Lookup=require('../web/part-lookup-ui.js');return {region:'US48',weightKg:weight,declaredValueUsd:'',lengthCm:'',widthCm:'',heightCm:'',partLookup:Lookup.validateState({...Lookup.emptyState(),forms:{standalone:{make:'TOYOTA',part}}})};}
function queueFixture(){const a={id:'TOYOTA:90915-10001',manufacturer:'TOYOTA',partNumber:'90915-10001',status:'researching',note:'',draft:draft('90915-10001','1')},b={...a,id:'TOYOTA:90915-10002',partNumber:'90915-10002',draft:draft('90915-10002','9')};return {version:1,activeId:a.id,items:[a,b]};}
function seedDocuments(queue,shipping){const seed={[queueKey]:JSON.stringify(queue),[shippingKey]:JSON.stringify(shipping)};for(const [namespace,data]of [['queue',queue],['shipping',shipping]])seed[`part-scout-sync-v1:${namespace}`]=JSON.stringify({version:1,userKey:'alice',baseRevision:1,baseData:data,pending:null,conflict:null,attempt:null,updatedAt:'2026-09-08T00:00:00.000Z'});return seed;}
function responseDoc(data,revision=1){return {status:200,json:async()=>({schemaVersion:1,userKey:'alice',revision,data,updatedAt:'2026-09-08T00:00:00.000Z'})};}
test('queue receive changes work position without reassigning the displayed shipping draft',async()=>{
  const queue=queueFixture();let cloudQueue=queue,revision=1;const shipping=queue.items[0].draft;
  const dom=open(seedDocuments(queue,shipping),async url=>responseDoc(url.endsWith('/queue')?cloudQueue:shipping,url.endsWith('/queue')?revision:1));const w=dom.window;await tick();
  cloudQueue={...queue,activeId:queue.items[1].id};revision=2;w.document.querySelector('[data-queue-sync] [data-sync-now]').click();await tick();input(w,'[name=weightKg]','2');
  const saved=JSON.parse(w.localStorage.getItem(queueKey));assert.equal(saved.items[0].draft.weightKg,'2');assert.equal(saved.items[1].draft.weightKg,'9');
  w.document.querySelectorAll('.research-item')[1].querySelector('button').click();assert.equal(w.document.querySelector('[name=weightKg]').value,'9');dom.window.close();
});
test('URL resume establishes the actual owner, survives reload, and preserves the previous owner',async()=>{
  const queue=queueFixture(),seed=seedDocuments(queue,queue.items[0].draft),url='https://live.test/shipping-calculator.html?research='+encodeURIComponent(queue.items[1].id);
  let dom=open(seed,undefined,{url}),w=dom.window;input(w,'[name=weightKg]','8');let saved=JSON.parse(w.localStorage.getItem(queueKey));assert.equal(saved.items[0].draft.weightKg,'1');assert.equal(saved.items[1].draft.weightKg,'8');
  const reopenedSeed=Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));dom.window.close();dom=open(reopenedSeed,undefined,{url});w=dom.window;input(w,'[name=weightKg]','7');saved=JSON.parse(w.localStorage.getItem(queueKey));assert.equal(saved.items[0].draft.weightKg,'1');assert.equal(saved.items[1].draft.weightKg,'7');dom.window.close();
});
for(const order of ['queue-first','shipping-first'])test(`independent ${order} cloud arrival detaches shipping attribution`,async()=>{
  const queue=queueFixture(),shipping=queue.items[0].draft;let releaseQueue,releaseShipping;
  const incoming={...queue,activeId:queue.items[1].id};const dom=open(seedDocuments(queue,shipping),url=>new Promise(resolve=>{if(url.endsWith('/queue'))releaseQueue=()=>resolve(responseDoc(incoming,2));else releaseShipping=()=>resolve(responseDoc(draft('90915-10002','6'),2));}));const w=dom.window;
  if(order==='queue-first'){releaseQueue();await tick();releaseShipping();}else{releaseShipping();await tick();releaseQueue();}await tick();
  assert.equal(w.document.querySelector('[name=weightKg]').value,'6');input(w,'[name=weightKg]','5');const saved=JSON.parse(w.localStorage.getItem(queueKey));assert.equal(saved.items[0].draft.weightKg,'1');assert.equal(saved.items[1].draft.weightKg,'9');
  w.document.querySelectorAll('.research-item')[1].querySelector('button').click();assert.equal(w.document.querySelector('[name=weightKg]').value,'9');dom.window.close();
});
test('manual lookup identity change detaches the queue owner before the next parcel edit',()=>{
  const queue=queueFixture(),dom=open(seedDocuments(queue,queue.items[0].draft)),w=dom.window;w.document.querySelectorAll('.research-item')[0].querySelector('button').click();
  input(w,'[data-lookup-field=part]','90915-10002');input(w,'[name=weightKg]','4');const saved=JSON.parse(w.localStorage.getItem(queueKey));assert.equal(saved.items[0].draft.weightKg,'1');assert.equal(saved.items[1].draft.weightKg,'9');dom.window.close();
});
function sharedStorage(){const rows=new Map();return {getItem:k=>rows.get(k)??null,setItem:(k,v)=>rows.set(k,String(v))};}
test('ordinary shipping writes from a stale form preserve the real durable value permanently',()=>{
  const shared=sharedStorage();shared.setItem(shippingKey,JSON.stringify(draft('90915-10001','1')));const a=open({},undefined,{storage:shared}),b=open({},undefined,{storage:shared});
  input(a.window,'[name=weightKg]','UNSENT_A');input(b.window,'[name=weightKg]','NEW_B');assert.equal(JSON.parse(shared.getItem(shippingKey)).weightKg,'UNSENT_A');
  a.window.close();const reopened=open({},undefined,{storage:shared});input(reopened.window,'[name=weightKg]','LATER');const history=JSON.parse(shared.getItem(shippingKey+':conflicts'));assert.equal(history[0].remote.weightKg,'UNSENT_A');assert.equal(history[0].local.weightKg,'NEW_B');
  b.window.close();reopened.window.close();
});
function openMain(shared){const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://live.test/',runScripts:'outside-only'}),w=dom.window;Object.defineProperty(w,'localStorage',{value:shared});w.scrollTo=()=>{};w.fetch=async()=>({status:404,ok:false,json:async()=>({})});for(const f of ['persistence.js','shipping.js','part-parcel.js','part-lookup-ui.js','workspace-sync.js','research-queue.js','app.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));return dom;}
test('ordinary main settings writes from a stale form preserve both versions permanently',()=>{
  const shared=sharedStorage(),a=openMain(shared);input(a.window,'[name=minimumProfitJpy]','1');const b=openMain(shared);input(a.window,'[name=minimumProfitJpy]','333');input(b.window,'[name=minimumProfitJpy]','444');
  assert.equal(JSON.parse(shared.getItem('part-scout-user-v1')).settings.minimumProfitJpy,'333');const history=JSON.parse(shared.getItem('part-scout-user-v1:conflicts'));assert.equal(history[0].remote.settings.minimumProfitJpy,'333');assert.equal(history[0].local.settings.minimumProfitJpy,'444');a.window.close();b.window.close();
});
for(const order of ['queue-first','shipping-first'])test(`URL resume waits for a missing queued item with ${order} delivery and preserves the displaced estimate`,async()=>{
  const queue=queueFixture();let releaseQueue,releaseShipping;const url='https://live.test/shipping-calculator.html?research='+encodeURIComponent(queue.items[1].id);
  const dom=open({},path=>new Promise(resolve=>{if(path.endsWith('/queue'))releaseQueue=()=>resolve(responseDoc(queue));else releaseShipping=()=>resolve(responseDoc(draft('90915-10001','6')));}),{url}),w=dom.window;
  if(order==='queue-first'){releaseQueue();await tick();releaseShipping();}else{releaseShipping();await tick();releaseQueue();}await tick();await tick();
  assert.equal(w.document.querySelector('[name=weightKg]').value,'9');input(w,'[name=weightKg]','8');
  assert.equal(JSON.parse(w.localStorage.getItem(queueKey)).items[1].draft.weightKg,'8');
  if(order==='shipping-first'){const history=JSON.parse(w.localStorage.getItem(shippingKey+':conflicts'));assert.ok(history.some(x=>x.local.weightKg==='6'));}
  dom.window.close();
});
test('shipping cloud receive cannot replace a different durable domain value even with unchanged sync metadata',async()=>{
  const queue=queueFixture(),initial=queue.items[0].draft,shared=sharedStorage();let remote=initial,revision=1;
  const dom=open(seedDocuments(queue,initial),async url=>responseDoc(url.endsWith('/queue')?queue:remote,url.endsWith('/queue')?1:revision),{storage:shared}),w=dom.window;await tick();
  shared.setItem(shippingKey,JSON.stringify(draft('90915-10001','UNSENT_A')));remote=draft('90915-10001','REMOTE_C');revision=2;w.document.querySelector('#shipping-sync [data-sync-now]').click();await tick();
  assert.equal(JSON.parse(shared.getItem(shippingKey)).weightKg,'UNSENT_A');assert.equal(w.document.querySelector('[name=weightKg]').value,'1');
  const archive=JSON.parse(shared.getItem(shippingKey+':conflicts'));assert.equal(archive[0].remote.weightKg,'UNSENT_A');assert.equal(archive[0].local.weightKg,'REMOTE_C');
  const details=w.document.querySelector('#shipping-sync details');details.open=true;details.dispatchEvent(new w.Event('toggle'));assert.match(w.document.querySelector('#shipping-sync [data-sync-version]').textContent,/別タブの保存/);await tick();dom.window.close();
});
test('shipping backup import detaches the previous task before further parcel edits',async()=>{
  const queue=queueFixture(),dom=open(seedDocuments(queue,queue.items[0].draft)),w=dom.window;const file=w.document.querySelector('#calc-file');Object.defineProperty(file,'files',{value:[{size:100,text:async()=>JSON.stringify({format:shippingKey,data:draft('90915-10002','6')})}]});file.dispatchEvent(new w.Event('change'));await tick();input(w,'[name=weightKg]','5');const saved=JSON.parse(w.localStorage.getItem(queueKey));assert.equal(saved.items[0].draft.weightKg,'1');assert.equal(saved.items[1].draft.weightKg,'9');dom.window.close();
});
